[tool.black]
line-length = 100
exclude = """
.eggs/
| .git/
| .tox/
| .venv/
| _build/
| build/
| dist/
| _sandbox/
| docs/conf.py
| setup.py
"""

[tool.coverage.run]
source = ['msgfy']
branch = true

[tool.coverage.report]
show_missing = true
precision = 1
exclude_lines = [
    'except ImportError',
    'raise NotImplementedError',
    'pass',
    'ABCmeta',
    'abstractmethod',
    'abstractproperty',
    'abstractclassmethod',
    'warnings.warn',
]
